# Generated by Django 6.1.1 on 2026-09-25 11:48

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('avatars'), validators=[core.uploads.validate_image]),
        ),
    ]
