# Generated by Django 6.1.1 on 2026-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='purpose',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('login', 'Kirish'), ('admin', 'Admin panel (2FA)')], max_length=10),
        ),
    ]
