# Generated by Django 6.1.1 on 2026-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin_2fa_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=2),
        ),
    ]
