# Generated by Django 5.2.17 on 2026-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
