# Generated by Django 6.1.1 on 2026-09-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumBotChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.PositiveIntegerField()),
                ('card_number', models.CharField(help_text="Pul o'tkazilgan karta", max_length=19)),
                ('payer_card_last4', models.CharField(blank=True, max_length=4)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('web', 'Sayt'), ('telegram', 'Telegram bot')], default='web', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
