# Generated by Django 6.1.1 on 2026-09-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumbotchat',
            name='is_admin',
            field=models.BooleanField(default=False, help_text="To'lovlarni tasdiqlaydigan admin"),
        ),
    ]
