# Generated by Django 6.1.1 on 2026-09-25 11:48

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_botchat_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpayment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('receipts'), validators=[core.uploads.validate_image]),
        ),
    ]
