# Generated by Django 6.1.1 on 2026-09-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('year', models.PositiveIntegerField(default=2020)),
                ('engine', models.CharField(blank=True, default='1.5L', max_length=20)),
                ('transmission', models.CharField(blank=True, default='Avtomat', max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('plate', models.CharField(blank=True, max_length=15)),
                ('vin', models.CharField(blank=True, max_length=20)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('next_service_km', models.PositiveIntegerField(default=1200)),
                ('oil_change_km', models.PositiveIntegerField(default=1200)),
                ('tire_km', models.PositiveIntegerField(default=8500)),
                ('inspection_km', models.PositiveIntegerField(default=12000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('master_name', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='garage.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
