# Generated by Django 6.1.1 on 2026-09-25 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('osago', "Sug'urta (OSAGO)"), ('kasko', 'KASKO'), ('texosmotr', "Texnik ko'rik"), ('ishonchnoma', 'Ishonchnoma'), ('tonirovka', 'Tonirovka ruxsatnomasi'), ('gaz', 'Gaz ballon guvohnomasi'), ('prava', 'Haydovchilik guvohnomasi'), ('boshqa', 'Boshqa')], default='osago', max_length=12)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('expires_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('last_reminded', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='garage.vehicle')),
            ],
            options={
                'ordering': ['expires_on'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('yoqilgi', "Yoqilg'i"), ('servis', "Servis va ta'mir"), ('zapchast', 'Ehtiyot qism'), ('yuvish', 'Yuvish'), ('parkovka', 'Parkovka'), ('jarima', 'Jarima'), ('sugurta', "Sug'urta va hujjat"), ('boshqa', 'Boshqa')], default='yoqilgi', max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('liters', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='garage.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
