# Generated by Django 6.1.1 on 2026-09-25 11:48

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_documents_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('cars'), validators=[core.uploads.validate_image]),
        ),
    ]
