# Generated by Django 6.1.1 on 2026-09-26 09:11

from django.db import migrations, models


def clear_placeholder_values(apps, schema_editor):
    """Avval avtomatik qo'yilgan (egasi kiritmagan) servis km larini tozalaymiz — ular haqiqiy ma'lumot emas edi."""
    Vehicle = apps.get_model("garage", "Vehicle")
    placeholders = [(1200, 1200, 8500, 12000), (5000, 5000, 20000, 15000)]
    for ns, oc, tk, ik in placeholders:
        Vehicle.objects.filter(next_service_km=ns, oil_change_km=oc, tire_km=tk, inspection_km=ik).update(
            next_service_km=None, oil_change_km=None, tire_km=None, inspection_km=None)


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inspection_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='next_service_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='oil_change_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tire_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(clear_placeholder_values, migrations.RunPython.noop),
    ]
