# Generated by Django 6.1.1 on 2026-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_honest_service_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
