# Generated by Django 6.1.1 on 2026-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_servicerecord_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('metan', 'Metan'), ('propan', 'Propan'), ('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektr', 'Elektr')], default='', max_length=10),
        ),
    ]
