# Generated by Django 6.1.1 on 2026-09-25 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MasterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='masters.masterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
