# Generated by Django 6.1.1 on 2026-09-25 11:48

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_reminders_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterphoto',
            name='image',
            field=models.ImageField(upload_to=core.uploads.UploadTo('portfolio'), validators=[core.uploads.validate_image]),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('masters'), validators=[core.uploads.validate_image]),
        ),
    ]
