# Generated by Django 6.1.1 on 2026-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_masterphoto_image_alter_masterprofile_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
