# Generated by Django 6.1.1 on 2026-09-30 03:23

import core.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_booking_note_alter_masterprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterphoto',
            name='before',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('portfolio'), validators=[core.uploads.validate_image]),
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.uploads.UploadTo('reviews'), validators=[core.uploads.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='masters.review')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
