# Generated by Django 6.1.1 on 2026-09-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_photos_before_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='work_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
