# Generated by Django 5.2.17 on 2026-10-04 08:29

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0007_stories"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="duration",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.uploads.VideoUploadTo("stories-video"),
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=core.uploads.UploadTo("stories"),
                validators=[core.uploads.validate_image],
            ),
        ),
    ]
