# Generated by Django 5.2.18 on 2026-10-10 13:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField()),
                ("letter", models.CharField(max_length=4)),
                ("room", models.CharField(blank=True, max_length=20)),
                (
                    "shift",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1-smena"), (2, "2-smena")], default=1
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["grade", "letter"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Maktab", max_length=150)),
                ("short_name", models.CharField(blank=True, max_length=40)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("logo", models.CharField(blank=True, max_length=255)),
                ("academic_year", models.CharField(default="2026-2027", max_length=20)),
                ("work_days", models.JSONField(default=list)),
                ("work_start", models.TimeField(default=datetime.time(8, 0))),
                ("work_end", models.TimeField(default=datetime.time(17, 0))),
                ("late_grace_minutes", models.PositiveSmallIntegerField(default=5)),
                (
                    "arrive_before_lesson_minutes",
                    models.PositiveSmallIntegerField(default=10),
                ),
                ("use_timetable_for_arrival", models.BooleanField(default=True)),
                (
                    "absent_alert_after_minutes",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("checkout_min_minutes", models.PositiveSmallIntegerField(default=60)),
                ("face_threshold", models.FloatField(default=0.48)),
                ("require_liveness", models.BooleanField(default=True)),
                ("store_checkin_photos", models.BooleanField(default=True)),
                ("photo_retention_days", models.PositiveSmallIntegerField(default=30)),
                ("daily_report_time", models.TimeField(default=datetime.time(18, 0))),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("short", models.CharField(blank=True, max_length=12)),
                ("color", models.CharField(default="#6366F1", max_length=9)),
                ("icon", models.CharField(default="book", max_length=32)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("meeting", "Yig'ilish"),
                            ("exam", "Imtihon / nazorat"),
                            ("event", "Tadbir"),
                            ("holiday", "Bayram / dam olish"),
                            ("parents", "Ota-onalar majlisi"),
                        ],
                        default="meeting",
                        max_length=10,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Hammaga"),
                            ("staff", "O'qituvchilarga"),
                            ("students", "O'quvchilarga"),
                            ("classes", "Tanlangan sinflarga"),
                        ],
                        default="staff",
                        max_length=10,
                    ),
                ),
                ("reminded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="school.schoolclass"
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Hammaga"),
                            ("staff", "O'qituvchilarga"),
                            ("students", "O'quvchilarga"),
                            ("classes", "Tanlangan sinflarga"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("important", models.BooleanField(default=False)),
                ("attachment", models.CharField(blank=True, max_length=255)),
                ("attachment_name", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(default="web", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="school.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_no", models.CharField(blank=True, max_length=20)),
                ("parent_name", models.CharField(blank=True, max_length=120)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="school.schoolclass",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(default="O'qituvchi", max_length=80)),
                ("category", models.CharField(blank=True, max_length=40)),
                ("hired_at", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("pin_hash", models.CharField(blank=True, max_length=200)),
                ("pin_failed", models.PositiveSmallIntegerField(default=0)),
                ("pin_locked_until", models.DateTimeField(blank=True, null=True)),
                ("track_attendance", models.BooleanField(default=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="school.subject"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to="school.teacherprofile",
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Dushanba"),
                            (2, "Seshanba"),
                            (3, "Chorshanba"),
                            (4, "Payshanba"),
                            (5, "Juma"),
                            (6, "Shanba"),
                            (7, "Yakshanba"),
                        ]
                    ),
                ),
                ("period", models.PositiveSmallIntegerField()),
                ("room", models.CharField(blank=True, max_length=20)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="school.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="school.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="school.teacherprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "period"],
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours_per_week", models.PositiveSmallIntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="school.teacherprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "school_class__grade",
                    "school_class__letter",
                    "subject__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="school_noti_user_id_346242_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("grade", "letter"), name="uniq_class_grade_letter"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("school_class", "weekday", "period"), name="uniq_lesson_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(
                fields=("school_class", "subject"), name="uniq_class_subject_teacher"
            ),
        ),
    ]
