# Generated by Django 6.1.1 on 2026-09-25 11:48

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('products'), validators=[core.uploads.validate_image]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.uploads.UploadTo('shops'), validators=[core.uploads.validate_image]),
        ),
    ]
