# Generated by Django 6.1.1 on 2026-09-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_model', models.CharField(blank=True, max_length=60)),
                ('plate', models.CharField(blank=True, max_length=15)),
                ('base_price', models.PositiveIntegerField(default=150000)),
                ('price_per_km', models.PositiveIntegerField(default=10000)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=5.0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evacuator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('evakuator', 'Evakuator'), ('tezkor_usta', 'Tezkor usta'), ('diagnostika', 'Diagnostika')], default='evakuator', max_length=12)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('searching', 'Qidirilmoqda'), ('accepted', 'Qabul qilindi'), ('on_the_way', "Yo'lda"), ('arrived', 'Yetib keldi'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='searching', max_length=12)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
