# Generated by Django 6.1.1 on 2026-09-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuatorprofile',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='review',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='evacuatorprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
