# Generated by Django 6.1.1 on 2026-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuator', '0002_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
