# Generated by Django 6.1.1 on 2026-09-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0006_vehicle_fuel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('metan', 'Metan'), ('propan', 'Propan'), ('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektr', 'Elektr')], default='metan', max_length=10)),
                ('start_name', models.CharField(max_length=120)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('dest_name', models.CharField(max_length=120)),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('route', models.JSONField(default=list)),
                ('stations', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
                ('distance_km', models.FloatField(default=0)),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Davom etmoqda'), ('finished', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('progress_km', models.FloatField(default=0)),
                ('fuel_stops', models.PositiveSmallIntegerField(default=0)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='garage.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TripSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('voice', models.BooleanField(default=True)),
                ('fuel_alerts', models.BooleanField(default=True)),
                ('safety_alerts', models.BooleanField(default=True)),
                ('periodic', models.BooleanField(default=True)),
                ('interval_min', models.PositiveSmallIntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('start', 'Boshlanish'), ('fuel', "Yoqilg'i"), ('gap', "Yoqilg'i ogohlantirishi"), ('safety', 'Xavfsizlik'), ('service', 'Servis'), ('arrive', 'Manzil'), ('finish', 'Yakun')], max_length=10)),
                ('message', models.CharField(max_length=240)),
                ('trigger_km', models.FloatField(blank=True, null=True)),
                ('trigger_min', models.PositiveIntegerField(blank=True, null=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('dedup_key', models.CharField(max_length=80)),
                ('spoken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trips.trip')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'dedup_key'), name='trip_notification_once')],
            },
        ),
    ]
