"""Ustalar hikoyalari sinovi: joylash (rasm va video), ko'rish (progress, tap, orqaga), ko'rildi belgisi, tahrirlash, o'chirish."""
import json, os, re
from playwright.sync_api import sync_playwright
S=os.environ.get("STORY_DIR", "/tmp/avtora-story-test")
B="http://localhost:8800"; IDS=json.load(open(S+"/ids.json")); R=[]
def check(n, ok, info=""): R.append(ok); print(("OK  " if ok else "FAIL"), n, info, flush=True)
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"], executable_path=os.getenv("CHROMIUM_PATH") or None); errs=[]
    def ctx(who, w=390, h=844):
        c=b.new_context(viewport={"width":w,"height":h}, is_mobile=w<600, has_touch=w<600)
        a,r=IDS[who]; c.add_init_script(f"localStorage.setItem('ah_access','{a}');localStorage.setItem('ah_refresh','{r}');localStorage.setItem('ah_intro_off','1');localStorage.setItem('ah_push_prompt_hidden_at','9999999999999');localStorage.setItem('ah_install_dismissed_at','9999999999999')")
        pg=c.new_page(); pg.set_default_timeout(10000); pg.on("pageerror", lambda e: errs.append(str(e)[:200]))
        pg.on("dialog", lambda d: d.accept()); return c, pg
    uc, U = ctx("usta"); cc, C = ctx("client")
    # mijoz: hikoya yo'q — qator ko'rinmaydi (joy egallamaydi)
    C.goto(B+"/app"); C.wait_for_timeout(2500)
    check("Hikoya yo'q bo'lsa mijozda qator ko'rinmaydi", C.locator(".stories").count()==0)
    # usta: joylash (2 ta)
    U.goto(B+"/app/usta"); U.get_by_role("button", name="Hikoya qo'shish").click()
    U.locator(".sc-pick").wait_for(); U.screenshot(path=S+"/composer-pick.png")
    check("Joylash oynasi: Rasm olish / Video olish / Galereya", all(U.get_by_text(t, exact=True).count()==1 for t in ["Rasm olish","Video olish","Galereya"]))
    U.locator(".sc-full input[type=file]:not([capture])").set_input_files(S+"/v70.webm")
    U.get_by_text("soniyagacha bo'ladi").wait_for()
    check("60 soniyadan uzun video rad etiladi", U.locator(".sc-stage").count()==0)
    U.locator(".sc-full input[type=file]:not([capture])").set_input_files(S+"/story1.jpg")
    U.get_by_role("button", name="Matn yozish").click(); U.locator(".sc-typing textarea").fill("Bugun motor diagnostikasi 20% chegirma"); U.get_by_role("button", name="Tayyor").click()
    U.screenshot(path=S+"/composer.png")
    check("Instagram uslubi: orqaga, Aa, izoh, «Hikoyangiz» + ko'k tugma", U.locator(".sc-back").count()==1 and U.locator(".sc-pill", has_text="Hikoyangiz").count()==1 and U.locator(".sc-go").count()==1 and U.locator(".sc-stage .sv-caption").inner_text().startswith("Bugun"))
    U.get_by_role("button", name="Joylash").click()
    U.get_by_text("Hikoya joylandi").wait_for()
    U.get_by_role("button", name="Hikoya qo'shish").click(); U.locator(".sc-full input[type=file]:not([capture])").set_input_files(S+"/story2.jpg"); U.locator(".sc-go").click()
    U.locator(".sc-full").wait_for(state="detached")
    U.get_by_role("button", name="Hikoya qo'shish").click(); U.locator(".sc-full input[type=file]:not([capture])").set_input_files(S+"/v4.webm")
    U.locator(".sc-stage video").wait_for(); U.locator(".sc-caption").fill("Video: ish jarayoni")
    check("Video tanlandi: ko'rib chiqish, ovoz tugmasi, uzunligi 0:04", U.locator(".sc-dur").inner_text()=="0:04" and U.locator(".sc-tools button").count()==3, U.locator(".sc-dur").inner_text())
    U.screenshot(path=S+"/composer-video.png")
    U.locator(".sc-pill").click(); U.locator(".sc-full").wait_for(state="detached")
    U.locator(".story-tile", has_text="Sizning hikoyangiz").wait_for()
    check("Usta 3 ta hikoya joyladi (2 rasm + video), qatorda «Sizning hikoyangiz»", True)
    U.screenshot(path=S+"/usta-bar.png")
    # mijoz: rangli halqa → ko'rish
    C.reload(); C.locator(".story-tile", has_text="Rustam").wait_for()
    check("Mijozda rangli halqa (ko'rilmagan)", "seen" not in C.locator(".story-tile", has_text="Rustam").locator(".story-ring").get_attribute("class"))
    C.locator(".story-tile", has_text="Rustam").click(); C.locator(".story-viewer").wait_for()
    C.get_by_text("20% chegirma").wait_for()
    C.wait_for_timeout(1500); C.screenshot(path=S+"/viewer.png")
    w=C.evaluate("()=>document.querySelector('.sv-bars span i').style.width")
    check("Ko'rish oynasi: matn, progress chizig'i harakatda", w not in ("0%",""), w)
    C.locator(".sv-media").click(position={"x":330,"y":300}); C.wait_for_timeout(400)
    check("O'ngga bosish — keyingi hikoya", C.evaluate("()=>document.querySelectorAll('.sv-bars span i')[1].style.width")!="0%" and C.get_by_text("20% chegirma").count()==0)
    C.locator(".sv-media").click(position={"x":40,"y":300}); C.wait_for_timeout(400)
    check("Chapga bosish — oldingi hikoya", C.get_by_text("20% chegirma").count()==1)
    C.locator(".sv-media").click(position={"x":330,"y":300}); C.get_by_text("Video: ish jarayoni").wait_for(); C.wait_for_timeout(1500)
    vt=C.evaluate("()=>{const v=document.querySelector('.sv-media video'); return v && {t:v.currentTime, paused:v.paused}}")
    check("Video hikoya ijro etiladi, progress video bo'yicha", bool(vt) and vt["t"]>0.5 and not vt["paused"] and C.evaluate("()=>document.querySelectorAll('.sv-bars span i')[2].style.width")!="0%", str(vt))
    check("Video uchun ovoz tugmasi", C.locator(".sv-head button[aria-label*='Ovoz']").count()==1)
    src=C.evaluate("()=>document.querySelector('.sv-media video').src")
    st=C.evaluate("async(u)=>{const r=await fetch(u,{headers:{Range:'bytes=0-99'}}); return [r.status, r.headers.get('content-range'), (await r.arrayBuffer()).byteLength]}", src)
    check("Video Range bilan beriladi (iPhone uchun 206)", st[0]==206 and st[2]==100, str(st))
    C.go_back(); C.wait_for_timeout(500)
    check("Telefonning «orqaga» tugmasi oynani yopadi, sahifada qoladi", C.locator(".story-viewer").count()==0 and C.url.endswith("/app"))
    C.wait_for_timeout(500)
    check("Ko'rilgandan keyin halqa kulrang", "seen" in (C.locator(".story-tile", has_text="Rustam").locator(".story-ring").get_attribute("class") or ""))
    # avtomatik o'tish va yopilish
    C.locator(".story-tile", has_text="Rustam").click(); C.locator(".story-viewer").wait_for(); C.wait_for_timeout(19500)
    check("Avtomatik o'tib, oxirida o'zi yopiladi", C.locator(".story-viewer").count()==0)
    # usta: ko'rishlar soni, tahrirlash
    U.reload(); U.locator(".story-tile", has_text="Sizning hikoyangiz").click(); U.locator(".story-viewer").wait_for()
    check("Usta ko'rishlar sonini ko'radi", U.locator(".sv-meta").first.inner_text().strip()=="1", U.locator(".sv-meta").first.inner_text())
    check("Qolgan vaqt ko'rsatiladi (~23 soat)", "soat qoldi" in U.locator(".sv-meta").nth(1).inner_text())
    U.get_by_role("button", name="Tahrirlash").click(); U.locator(".sc-stage").wait_for(); U.screenshot(path=S+"/composer-edit.png"); U.locator(".sc-caption").fill("Bugun motor diagnostikasi 30% chegirma!"); U.locator(".sc-go").click()
    U.get_by_text("Hikoya yangilandi").wait_for()
    C.reload(); C.locator(".story-tile", has_text="Rustam").click(); C.get_by_text("30% chegirma!").wait_for()
    check("Tahrir mijozda ko'rinadi + «tahrirlangan»", "tahrirlangan" in C.locator(".sv-head").inner_text())
    C.keyboard.press("Escape")
    # o'chirish
    U.locator(".story-tile", has_text="Sizning hikoyangiz").click(); U.locator(".story-viewer").wait_for(); U.get_by_role("button", name="O'chirish", exact=True).click()
    U.get_by_text("Hikoya o'chirildi").wait_for()
    U.locator(".story-tile", has_text="Sizning hikoyangiz").click(); U.locator(".story-viewer").wait_for(); U.get_by_role("button", name="O'chirish", exact=True).click(); U.get_by_text("Hikoya o'chirildi").first.wait_for()
    U.wait_for_timeout(800)
    U.locator(".story-tile", has_text="Sizning hikoyangiz").click(); U.locator(".story-viewer").wait_for(); U.get_by_role("button", name="O'chirish", exact=True).click(); U.wait_for_timeout(1200)
    C.reload(); C.wait_for_timeout(2500)
    check("O'chirilgach mijozda hikoya yo'q", C.locator(".story-tile", has_text="Rustam").count()==0)
    # desktop ko'rinish
    dc, D = ctx("usta", 1280, 800); D.goto(B+"/app/usta"); D.locator(".stories").wait_for(); D.wait_for_timeout(600); D.screenshot(path=S+"/usta-desktop.png"); dc.close()
    check("Sahifa xatolari yo'q", not errs, str(errs[:3]))
    b.close()
print(f"=== NATIJA: {sum(R)} / {len(R)} ===")
