# Generated by Django 6.1.1 on 2026-09-25 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('lat', models.FloatField(db_index=True)),
                ('lng', models.FloatField(db_index=True)),
                ('fuels', models.JSONField(default=list)),
                ('is_24_7', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(default='user', max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('metan', 'Metan'), ('propan', 'Propan'), ('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektr', 'Elektr quvvatlash')], max_length=10)),
                ('status', models.CharField(choices=[('bor', 'Bor, navbatsiz'), ('navbat_kichik', 'Bor, navbat kichik'), ('navbat_katta', 'Bor, navbat katta'), ('yoq', "Yo'q"), ('yopiq', 'Yopiq')], max_length=15)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_reports', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fuel.fuelstation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['station', 'fuel', '-created_at'], name='fuel_fuelre_station_eeab55_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('metan', 'Metan'), ('propan', 'Propan'), ('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektr', 'Elektr quvvatlash')], default='metan', max_length=10)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='fuel.fuelstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'station', 'fuel')},
            },
        ),
    ]
