# Generated by Django 6.1.1 on 2026-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField(default=0)),
                ('added', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('deactivated', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='overpass', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='fuels_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
