# Generated by Django 6.1.1 on 2026-09-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('maslahat', 'Maslahat'), ('yangilik', 'Yangiliklar'), ('texnik', 'Texnik xizmat'), ('qonun', 'Qonunlar')], default='maslahat', max_length=12)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AVTOHUB', max_length=60)),
                ('tagline', models.CharField(default='Avtomobilingiz uchun barcha xizmatlar — bir joyda', max_length=160)),
                ('currency', models.CharField(default="so'm", max_length=10)),
                ('support_phone', models.CharField(default='+998 71 200 00 00', max_length=20)),
                ('premium_price', models.PositiveIntegerField(default=40000)),
                ('card_number', models.CharField(default='4073420079545178', max_length=19)),
                ('card_holder', models.CharField(default='AVTOHUB', max_length=60)),
                ('sos_radius_km', models.PositiveIntegerField(default=30)),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order', 'Buyurtma'), ('sos', 'SOS'), ('chat', 'Xabar'), ('premium', 'Premium'), ('system', 'Tizim'), ('review', 'Reyting')], default='system', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
