# Generated by Django 6.1.1 on 2026-09-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
