# Generated by Django 6.1.1 on 2026-09-25 12:40

from django.db import migrations, models


def rename_brand(apps, schema_editor):
    """Mavjud bazada sayt nomi eski bo'lsa — Avtora ga almashtiramiz."""
    S = apps.get_model("core", "SiteSettings")
    S.objects.filter(site_name__iexact="AVTOHUB").update(site_name="Avtora")
    S.objects.filter(card_holder__iexact="AVTOHUB").update(card_holder="Avtora")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.RunPython(rename_brand, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sitesettings',
            name='card_holder',
            field=models.CharField(default='Avtora', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Avtora', max_length=60),
        ),
    ]
