# Generated by Django 6.1.1 on 2026-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rebrand_avtora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
