# Generated by Django 6.1.1 on 2026-09-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogpost_body_alter_notification_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_body',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_state',
            field=models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborildi'), ('none', "Qurilma yo'q"), ('failed', 'Xato'), ('off', 'Yuborilmaydi')], db_index=True, default='off', max_length=8),
        ),
        migrations.AddField(
            model_name='notification',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=700, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
