# Generated by Django 5.2.17 on 2026-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_web_push"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="last_error",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
